---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  require_chef_omnibus: 12

platforms:
  - name: win2012r2
    driver:
      box: postgred/win2012r2-standard-nocm

verifier:
  name: inspec

suites:
  - name: install
    run_list:
      - recipe[test::default]
