---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: win2012r2
    driver:
      box: postgred/win2012r2-standard-nocm

suites:
  - name: default
    run_list:
      - recipe[test::default]
