environment:
  machine_user: vagrant
  machine_pass: vagrant
  KITCHEN_YAML: .kitchen.appveyor.yml

branches:
  only:
    - master

skip_tags: true

clone_depth: 1

install:
  - ps: . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; Install-Project -Project chefdk -channel stable -version 1.2.20
  - ps: 'Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version'
  - ps: $PSVersionTable
  - c:\opscode\chefdk\bin\chef.bat exec ruby --version

build_script:
  - ps: c:\opscode\chefdk\bin\chef.bat shell-init powershell | iex; cmd /c c:\opscode\chefdk\bin\chef.bat --version

test_script:
  - c:\opscode\chefdk\bin\cookstyle --version
  - c:\opscode\chefdk\bin\chef.bat exec foodcritic --version
  - c:\opscode\chefdk\bin\chef.bat exec kitchen verify

deploy: off
